### ISSUE TITLE
outline broken in vscode

### ISSUE THREAD

**Issue by robert-boulanger** [phil294/coffeesense#7]
It seems the outline view in vscode is broken in combination with coffeesense
See the attached picture. It show a class with several member functions which all are nested in each other inside the outline view.
Also go to editor symbols (Shift-Cmd-P @) or Cmd-F12 does not work as expected. Symbos are shown, but any symbol inside the class body can not be targeted
![Bildschirmfoto 2022-01-29 um 19 14 29](https://user-images.githubusercontent.com/6568445/151672723-7520a54b-cf7a-4c58-8330-b1d6cb3858c9.png)
.

**Comment by phil294** [comment]
Yes, they are not really useful. Implementing proper symbols is not quite easy and bug-prone I suppose, but I haven't invested too much time into it either.
Outline is based on symbols, and readme says about these:

> Document symbols: Usable but not great. Check out [Yorkxin's extension](https://github.com/yorkxin/vscode-coffeescript-support), it provides much better symbols if you need that

and I'd stick to that. Both extensions should get along just fine. It's a bit of waste of processor resources, but I wouldn't worry about that too much, as CoffeeSense is highly inefficient on its own already, due to the way it works internally.

**Comment by phil294** [comment]
fyi in some of the recent releases, I have completely removed outline (document symbols) in order for the new sticky scroll feature of VSCode to nicely work, based on indentation.

As it stands, for this feature, I would still recommend the above linked extension by Yorkxin. It's now even deprecated (kindly in favor of CoffeeSense), but one can still install it.
